#RESOURCE VERSIONINFO
#RESOURCE FILEVERSION 10, 1, 0, 8351
#RESOURCE PRODUCTVERSION 10, 1, 0, 8351
#RESOURCE STRINGINFO  "0409", "04E4"
#RESOURCE VERSION$ "CompanyName",      "SPFLite"
#RESOURCE VERSION$ "FileDescription",  "SPFLite Editor"
#RESOURCE VERSION$ "FileVersion",      "10.1.8351"
#RESOURCE VERSION$ "InternalName",     "SPFLite"
#RESOURCE VERSION$ "OriginalFilename", "SPFLite"
#RESOURCE VERSION$ "LegalCopyright",   "© 2014-2018 George D. Deluca, Robert L. Hodge"
#RESOURCE VERSION$ "ProductName",      "SPFLite"
#RESOURCE VERSION$ "ProductVersion",   "10.1.8351"
#RESOURCE VERSION$ "Comments",         "None"
#RESOURCE VERSION$ "Author",           "George D Deluca"
#RESOURCE VERSION$ "VersionDate",      "20181216"
#RESOURCE VERSION$ "Compiler",         "PowerBasic 10.04.0108"
